baseURL: ""
languageCode: en-us
title: Bruno Veloso
theme: hugo-coder

menu:
  main:
    - identifier: publications
      name: Publications
      url: /publications/
      weight: 1
    - identifier: teaching
      name: Teaching
      url: /teaching/
      weight: 2
