baseURL: ""
languageCode: en-us
title: Bruno Veloso
theme: hugo-coder
languageCode: "en"
defaultContentLanguage: "en"
pygmentsStyle: "bw"
pygmentsCodeFences: true
pygmentsCodeFencesGuessSyntax: true
enableEmoji: true


Params:
  description: "Bruno Veloso personal website"
  info: ["Machine Learning", "Data Streams"]
  avatarURL: "/images/bv.jpg"
  rtl: false
  colorScheme: "white"
  hideColorSchemeToggle: false
  maxSeeAlsoItems: 5



menu:
  main:
    - identifier: research
      name: Research
      url: /research
      weight: 10
    - identifier: teaching
      name: Teaching
      url: /teaching
      weight: 20
